In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_csv("student-scores.csv")

In [3]:
df = df1.copy()
df.head()

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76

In [4]:
df.drop(columns = ['id','first_name', 'last_name', 'email'],axis = 1, inplace=True)

In [5]:
df.columns

Index(['gender', 'part_time_job', 'absence_days', 'extracurricular_activities',
       'weekly_self_study_hours', 'career_aspiration', 'math_score',
       'history_score', 'physics_score', 'chemistry_score', 'biology_score',
       'english_score', 'geography_score'],
      dtype='object')

In [6]:
df['total_score'] = df['math_score'] + df['history_score'] + df['physics_score'] + df['chemistry_score'] + df['biology_score'] + df['english_score'] + df['geography_score']
df['avg_score'] = df['total_score']/7
df.head()

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,avg_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,574,82.000000
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,640,91.428571
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,605,86.428571
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86,551,78.714286
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,521,74.428571

In [7]:
df['career_aspiration'].unique()

array(['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
       'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
       'Banker', 'Writer', 'Accountant', 'Designer',
       'Construction Engineer', 'Game Developer', 'Stock Investor',
       'Real Estate Developer'], dtype=object)

In [8]:
df['career_aspiration'].value_counts()

career_aspiration
Software Engineer        315
Business Owner           309
Unknown                  223
Banker                   169
Lawyer                   138
Accountant               126
Doctor                   119
Real Estate Developer     83
Stock Investor            73
Construction Engineer     68
Artist                    67
Game Developer            63
Government Officer        61
Teacher                   59
Designer                  56
Scientist                 39
Writer                    32
Name: count, dtype: int64

In [9]:
len(df['career_aspiration'].unique())

17

In [10]:
df

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,avg_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,574,82.000000
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,640,91.428571
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,605,86.428571
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86,551,78.714286
4,male,False,5,False,10,Unknown,84,77,65,65,80,74,76,521,74.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,male,False,2,False,30,Construction Engineer,83,77,84,73,75,84,82,558,79.714286
1996,male,False,2,False,20,Software Engineer,89,65,73,80,87,67,73,534,76.285714
1997,female,False,5,False,14,Software Engineer,97,85,63,93,68,94,78,578,82.571429
1998,female,True,10,True,5,Business Owner,51,96,72,89,95,88,75,566,80.857143
1999,female,False,5,False,27,Accountant,82,99,91,69,83,93,100,617,88.142857

In [11]:
#Encoding Categorical columns manually using map
gender_map = {'male':0, 'female':1}
part_time_job_map = {False:0, True:1}
extracurricular_activity_map = {False:0, True:1}

career_aspiration_map = {
        'Lawyer': 0, 'Doctor': 1, 'Government Officer': 2, 'Artist': 3, 'Unknown': 4,
        'Software Engineer': 5, 'Teacher': 6, 'Business Owner': 7, 'Scientist': 8,
        'Banker': 9, 'Writer': 10, 'Accountant': 11, 'Designer': 12,
        'Construction Engineer': 13, 'Game Developer': 14, 'Stock Investor': 15,
        'Real Estate Developer': 16
    }

df['gender'] = df['gender'].map(gender_map)
df['part_time_job'] = df['part_time_job'].map(part_time_job_map)
df['extracurricular_activities'] = df['extracurricular_activities'].map(extracurricular_activity_map)
df['career_aspiration'] = df['career_aspiration'].map(career_aspiration_map)

In [12]:
df

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,total_score,avg_score
0,0,0,3,0,27,0,73,81,93,97,63,80,87,574,82.000000
1,1,0,2,0,47,1,90,86,96,100,90,88,90,640,91.428571
2,1,0,9,1,13,2,81,97,95,96,65,77,94,605,86.428571
3,1,0,5,0,3,3,71,74,88,80,89,63,86,551,78.714286
4,0,0,5,0,10,4,84,77,65,65,80,74,76,521,74.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0,0,2,0,30,13,83,77,84,73,75,84,82,558,79.714286
1996,0,0,2,0,20,5,89,65,73,80,87,67,73,534,76.285714
1997,1,0,5,0,14,5,97,85,63,93,68,94,78,578,82.571429
1998,1,1,10,1,5,7,51,96,72,89,95,88,75,566,80.857143
1999,1,0,5,0,27,11,82,99,91,69,83,93,100,617,88.142857

In [13]:
df.shape

(2000, 15)

In [14]:
df['career_aspiration'].value_counts()

career_aspiration
5     315
7     309
4     223
9     169
0     138
11    126
1     119
16     83
15     73
13     68
3      67
14     63
2      61
6      59
12     56
8      39
10     32
Name: count, dtype: int64

In [15]:
!pip install imblearn

Collecting imblearn
  Using cached imblearn-0.0-py2.py3-none-any.whl.metadata (355 bytes)
Collecting imbalanced-learn (from imblearn)
  Using cached imbalanced_learn-0.13.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: numpy<3,>=1.24.3 in c:\users\singh\pycharmprojects\education recommendor\.venv\lib\site-packages (from imbalanced-learn->imblearn) (2.2.4)
Collecting scipy<2,>=1.10.1 (from imbalanced-learn->imblearn)
  Using cached scipy-1.15.2-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting scikit-learn<2,>=1.3.2 (from imbalanced-learn->imblearn)
  Using cached scikit_learn-1.6.1-cp313-cp313-win_amd64.whl.metadata (15 kB)
Collecting sklearn-compat<1,>=0.1 (from imbalanced-learn->imblearn)
  Using cached sklearn_compat-0.1.3-py3-none-any.whl.metadata (18 kB)
Collecting joblib<2,>=1.1.1 (from imbalanced-learn->imblearn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl<4,>=2.0.0 (from imbalanced-learn->imblearn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached imblearn-0.0-py2.py3-none-any.whl (1.9 kB)
Using cached imbalanced_learn-0.13.0-py3-none-any.whl (238 kB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Using cached scikit_learn-1.6.1-cp313-cp313-win_amd64.whl (11.1 MB)
Using cached scipy-1.15.2-cp313-cp313-win_amd64.whl (41.0 MB)
Using cached sklearn_compat-0.1.3-py3-none-any.whl (18 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn, sklearn-compat, imbalanced-learn, imblearn
Successfully installed imbalanced-learn-0.13.0 imblearn-0.0 joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 sklearn-compat-0.1.3 threadpoolctl-3.6.0

In [16]:
df['career_aspiration'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
from imblearn.over_sampling import SMOTE

# Create SMOTE object
smote = SMOTE(random_state=42)

# Separate features and target variable
X = df.drop('career_aspiration', axis=1)
y = df['career_aspiration']

# Apply SMOTE to the data
X_resampled, y_resampled = smote.fit_resample(X, y)

In [18]:
X_resampled.shape

(5355, 14)

In [19]:
y_resampled.value_counts()

career_aspiration
0     315
1     315
2     315
3     315
4     315
5     315
6     315
7     315
8     315
9     315
10    315
11    315
12    315
13    315
14    315
15    315
16    315
Name: count, dtype: int64

In [20]:
y_resampled.shape

(5355,)

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2, random_state=42)

In [22]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4284, 14), (4284,), (1071, 14), (1071,))

In [23]:
#Feature Scalling
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
X_train_scaled.shape

(4284, 14)

In [25]:
X_train_scaled

array([[ 1.28299565, -0.25678162, -0.00818145, ...,  0.83256957,
         1.69738337,  1.70599861],
       [ 1.28299565, -0.25678162, -0.00818145, ..., -0.6591611 ,
        -0.80868961, -0.80947969],
       [ 1.28299565, -0.25678162, -0.93053284, ...,  1.29873541,
         1.92990561,  1.92101113],
       ...,
       [-0.77942587, -0.25678162,  0.91416993, ..., -0.19299527,
        -0.1111229 , -0.09747247],
       [ 1.28299565, -0.25678162, -0.00818145, ...,  0.64610324,
        -0.29197353, -0.28615629],
       [-0.77942587, -0.25678162,  0.45299424, ..., -0.28622844,
        -0.93786863, -0.94507273]], shape=(4284, 14))

In [28]:
#Models Training (Multiple Models)
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier": SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

# Train and evaluate each model
for name, model in models.items():
    print("="*50)
    print("Model:", name)
    # Train the model
    model.fit(X_train_scaled, y_train)

    # Predict on test set
    y_pred = model.predict(X_test_scaled)

    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    # Print metrics
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)

==================================================
Model: Logistic Regression
Accuracy: 0.4864612511671335
Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.54      0.49        68
           1       0.48      0.62      0.55        72
           2       0.42      0.44      0.43        57
           3       0.52      0.55      0.53        58
           4       0.33      0.17      0.22        66
           5       0.31      0.29      0.30        76
           6       0.58      0.92      0.71        71
           7       0.83      0.90      0.87        61
           8       0.42      0.47      0.45        53
           9       0.26      0.10      0.14        61
          10       0.59      0.71      0.65        63
          11       0.43      0.45      0.44        53
          12       0.31      0.16      0.21        68
          13       0.38      0.51      0.44        55
          14       0.61      0.93      0.74        57
          15       0.37      0.24      0.29        63
          16       0.55      0.32      0.40        69

    accuracy                           0.49      1071
   macro avg       0.46      0.49      0.46      1071
weighted avg       0.46      0.49      0.46      1071

Confusion Matrix:
 [[37  4  0  0  0  7  0  0  4  1 10  3  0  2  0  0  0]
 [ 2 45  0  0  0  7  0  0 13  0  0  0  0  5  0  0  0]
 [ 0  0 25  5  1  1  9  1  0  0  2  0  4  1  2  2  4]
 [ 0  0  2 32  0  0  3  1  0  0  0  0  0  0 11  0  9]
 [ 6  5  7  3 11  8  7  1  2  4  0  3  3  2  1  2  1]
 [ 9 11  0  0  1 22  1  0  0  7  1  5  3 12  0  4  0]
 [ 0  0  0  0  1  2 65  0  0  1  2  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0 55  0  0  0  0  0  0  3  0  0]
 [ 3 17  0  0  0  1  0  0 25  0  6  0  0  1  0  0  0]
 [11  1  0  0  3  6  8  0  1  6  2  9  6  6  0  2  0]
 [ 8  2  0  0  1  0  4  0  2  1 45  0  0  0  0  0  0]
 [ 0  1  0  0  4  6  3  0  4  1  0 24  1  3  0  6  0]
 [ 2  2  8  3  5  2  7  0  3  0  4  0 11  6  8  5  2]
 [ 1  2  1  0  3  0  0  0  5  1  1  4  4 28  0  5  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  0  0 53  0  1]
 [ 5  3  3  0  3  7  1  2  0  1  2  8  4  7  1 15  1]
 [ 0  0 13 13  0  1  5  6  0  0  1  0  0  0  8  0 22]]
==================================================
Model: Support Vector Classifier
Accuracy: 0.6470588235294118
Classification Report:
               precision    recall  f1-score   support

           0       0.55      0.59      0.57        68
           1       0.61      0.83      0.70        72
           2       0.60      0.74      0.66        57
           3       0.69      0.86      0.77        58
           4       0.58      0.17      0.26        66
           5       0.42      0.33      0.37        76
           6       0.70      0.93      0.80        71
           7       0.86      0.93      0.90        61
           8       0.65      0.81      0.72        53
           9       0.41      0.36      0.38        61
          10       0.84      0.86      0.85        63
          11       0.75      0.51      0.61        53
          12       0.64      0.51      0.57        68
          13       0.53      0.85      0.66        55
          14       0.77      0.93      0.84        57
          15       0.65      0.44      0.53        63
          16       0.77      0.48      0.59        69

    accuracy                           0.65      1071
   macro avg       0.65      0.66      0.63      1071
weighted avg       0.64      0.65      0.63      1071

Confusion Matrix:
 [[40  6  0  0  0  5  0  0  2  4  6  1  0  3  0  1  0]
 [ 1 60  0  0  0  2  0  0  5  0  0  0  1  3  0  0  0]
 [ 0  0 42  2  2  1  4  0  0  0  0  0  2  0  0  3  1]
 [ 0  0  2 50  0  0  0  1  0  0  0  0  0  0  3  0  2]
 [ 5  7  7  1 11  8  5  2  1  7  0  2  5  3  1  1  0]
 [ 9  7  1  0  0 25  1  1  5 12  0  3  1 10  0  1  0]
 [ 0  0  0  0  0  0 66  0  0  2  1  0  0  0  0  1  1]
 [ 0  0  0  1  0  0  1 57  0  0  0  0  0  0  1  0  1]
 [ 1  8  0  0  0  1  0  0 43  0  0  0  0  0  0  0  0]
 [ 8  1  1  0  0  5  6  1  3 22  1  0  4  5  0  4  0]
 [ 2  1  4  0  0  0  0  0  0  1 54  0  0  1  0  0  0]
 [ 0  3  1  0  3  5  0  1  3  2  1 27  1  3  0  3  0]
 [ 2  1  0  3  2  0  8  0  2  0  1  1 35  4  4  1  4]
 [ 0  3  0  0  0  1  0  0  2  1  0  1  0 47  0  0  0]
 [ 0  0  0  0  0  0  1  2  0  0  0  0  1  0 53  0  0]
 [ 5  2  3  0  1  5  0  0  0  3  0  1  4  9  1 28  1]
 [ 0  0  9 15  0  2  2  1  0  0  0  0  1  0  6  0 33]]
==================================================
Model: Random Forest Classifier
Accuracy: 0.8272642390289449
Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.87      0.81        68
           1       0.79      0.99      0.88        72
           2       0.75      0.98      0.85        57
           3       0.86      0.93      0.89        58
           4       0.82      0.47      0.60        66
           5       0.60      0.36      0.45        76
           6       0.91      0.99      0.95        71
           7       0.95      0.93      0.94        61
           8       0.73      0.98      0.84        53
           9       0.75      0.70      0.73        61
          10       0.94      0.97      0.95        63
          11       0.80      0.75      0.78        53
          12       0.93      0.84      0.88        68
          13       0.80      0.93      0.86        55
          14       0.89      0.98      0.93        57
          15       0.88      0.78      0.82        63
          16       0.88      0.75      0.81        69

    accuracy                           0.83      1071
   macro avg       0.83      0.84      0.82      1071
weighted avg       0.82      0.83      0.82      1071

Confusion Matrix:
 [[59  5  0  0  1  0  0  0  0  1  0  1  0  0  0  1  0]
 [ 0 71  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0 56  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0 54  0  0  0  1  0  0  0  0  0  0  2  0  1]
 [ 5  3  5  0 31  8  0  0  2  1  1  2  3  0  1  1  3]
 [ 4  6  0  0  3 27  1  0  7 11  1  3  0 10  0  3  0]
 [ 0  0  0  0  0  1 70  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 57  0  0  0  0  0  0  2  0  1]
 [ 0  1  0  0  0  0  0  0 52  0  0  0  0  0  0  0  0]
 [ 4  1  1  0  0  3  3  0  2 43  1  2  1  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  1  0 61  0  0  0  0  0  0]
 [ 0  2  0  0  3  3  1  0  3  0  0 40  0  1  0  0  0]
 [ 0  0  3  0  0  1  2  0  1  0  1  0 57  0  1  1  1]
 [ 0  0  2  0  0  0  0  0  1  0  0  0  0 51  0  1  0]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0 56  0  0]
 [ 4  1  2  0  0  2  0  0  0  1  0  2  0  2  0 49  0]
 [ 0  0  6  7  0  0  0  2  1  0  0  0  0  0  1  0 52]]
==================================================
Model: K Nearest Neighbors
Accuracy: 0.6760037348272643
Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.68      0.63        68
           1       0.72      0.76      0.74        72
           2       0.63      0.86      0.73        57
           3       0.60      0.81      0.69        58
           4       0.35      0.17      0.23        66
           5       0.34      0.14      0.20        76
           6       0.83      0.92      0.87        71
           7       0.90      0.72      0.80        61
           8       0.67      0.91      0.77        53
           9       0.43      0.48      0.45        61
          10       0.81      0.92      0.86        63
          11       0.70      0.62      0.66        53
          12       0.71      0.79      0.75        68
          13       0.69      0.80      0.74        55
          14       0.82      0.89      0.86        57
          15       0.65      0.62      0.63        63
          16       0.78      0.58      0.67        69

    accuracy                           0.68      1071
   macro avg       0.66      0.69      0.66      1071
weighted avg       0.66      0.68      0.66      1071

Confusion Matrix:
 [[46  2  0  0  0  3  0  0  1  8  6  0  0  0  0  2  0]
 [ 4 55  0  0  1  0  0  0  4  1  1  0  1  2  0  3  0]
 [ 0  0 49  1  0  0  0  0  0  0  2  0  0  0  1  1  3]
 [ 0  0  4 47  0  0  0  1  0  1  0  0  0  0  3  0  2]
 [ 4  5  5  5 11  6  6  1  2  7  1  1  6  1  1  1  3]
 [ 9  6  3  0  7 11  1  1  6 10  0  3  6  9  0  4  0]
 [ 0  0  1  2  0  0 65  0  0  2  0  0  0  0  1  0  0]
 [ 0  0  1  3  2  0  1 44  0  2  0  1  2  1  1  1  2]
 [ 1  4  0  0  0  0  0  0 48  0  0  0  0  0  0  0  0]
 [ 7  0  1  1  3  3  1  1  2 29  1  4  4  0  0  3  1]
 [ 2  0  2  0  0  0  0  0  0  1 58  0  0  0  0  0  0]
 [ 0  2  2  0  0  6  0  0  3  2  1 33  1  2  1  0  0]
 [ 1  1  2  2  0  0  1  0  0  2  1  1 54  0  0  3  0]
 [ 2  0  0  0  4  0  0  0  3  0  0  0  0 44  1  1  0]
 [ 0  0  1  1  0  1  0  0  0  0  0  0  1  1 51  1  0]
 [ 2  1  1  4  2  1  1  0  3  2  0  4  0  3  0 39  0]
 [ 0  0  6 12  1  1  2  1  0  0  1  0  1  1  2  1 40]]
==================================================
Model: Decision Tree Classifier
Accuracy: 0.6825396825396826
Classification Report:
               precision    recall  f1-score   support

           0       0.72      0.65      0.68        68
           1       0.74      0.89      0.81        72
           2       0.75      0.70      0.73        57
           3       0.81      0.76      0.79        58
           4       0.40      0.41      0.41        66
           5       0.41      0.28      0.33        76
           6       0.89      0.83      0.86        71
           7       0.92      0.77      0.84        61
           8       0.84      0.87      0.85        53
           9       0.41      0.52      0.46        61
          10       0.78      0.83      0.80        63
          11       0.55      0.66      0.60        53
          12       0.66      0.71      0.68        68
          13       0.70      0.76      0.73        55
          14       0.82      0.89      0.86        57
          15       0.53      0.44      0.48        63
          16       0.73      0.74      0.73        69

    accuracy                           0.68      1071
   macro avg       0.69      0.69      0.68      1071
weighted avg       0.68      0.68      0.68      1071

Confusion Matrix:
 [[44  5  0  0  1  6  0  0  1  4  2  0  2  1  0  2  0]
 [ 1 64  0  0  0  2  0  0  0  1  0  3  0  1  0  0  0]
 [ 0  0 40  0  0  1  0  1  0  5  0  0  3  0  0  3  4]
 [ 0  0  0 44  2  0  0  2  0  0  0  0  1  0  5  0  4]
 [ 2  2  5  0 27  3  1  0  1  6  1  5  4  1  1  3  4]
 [ 7  4  0  0  8 21  1  0  3 13  3  8  2  2  0  4  0]
 [ 0  0  1  0  4  2 59  0  0  2  1  0  2  0  0  0  0]
 [ 0  0  0  2  2  0  0 47  0  0  0  0  2  0  3  0  5]
 [ 0  5  0  0  0  0  0  0 46  0  1  1  0  0  0  0  0]
 [ 3  0  0  0  3  6  2  0  2 32  3  2  1  1  0  5  1]
 [ 1  1  0  0  0  0  0  0  0  6 52  0  1  2  0  0  0]
 [ 0  1  0  0  2  3  2  0  1  1  2 35  3  1  0  2  0]
 [ 0  0  1  1  8  1  0  0  1  3  0  1 48  0  1  3  0]
 [ 1  2  1  0  1  2  0  0  0  2  2  0  1 42  0  1  0]
 [ 0  0  1  2  0  0  0  0  0  0  0  0  2  0 51  0  1]
 [ 2  2  2  0  3  4  0  0  0  3  0  9  1  9  0 28  0]
 [ 0  0  2  5  6  0  1  1  0  0  0  0  0  0  1  2 51]]
==================================================
Model: Gaussian Naive Bayes
Accuracy: 0.3099906629318394
Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.22      0.32        68
           1       0.64      0.53      0.58        72
           2       0.18      0.05      0.08        57
           3       0.30      0.05      0.09        58
           4       0.50      0.06      0.11        66
           5       0.45      0.18      0.26        76
           6       0.31      1.00      0.47        71
           7       0.95      0.85      0.90        61
           8       0.64      0.17      0.27        53
           9       0.20      0.03      0.06        61
          10       0.69      0.35      0.46        63
          11       0.60      0.23      0.33        53
          12       0.50      0.13      0.21        68
          13       0.11      0.96      0.20        55
          14       0.00      0.00      0.00        57
          15       0.50      0.06      0.11        63
          16       0.47      0.30      0.37        69

    accuracy                           0.31      1071
   macro avg       0.45      0.31      0.28      1071
weighted avg       0.45      0.31      0.29      1071

Confusion Matrix:
 [[15  0  0  0  0  3  4  0  1  0  4  2  0 39  0  0  0]
 [ 0 38  0  0  0  2  3  0  3  0  0  0  2 24  0  0  0]
 [ 0  0  3  0  1  1 16  0  0  0  0  0  0 31  0  2  3]
 [ 0  0  0  3  0  0 15  1  0  0  0  0  0 23  3  0 13]
 [ 3  3  0  3  4  3 13  0  0  2  0  3  3 26  0  0  3]
 [ 4  6  0  0  1 14 12  0  0  2  0  1  1 34  0  1  0]
 [ 0  0  0  0  0  0 71  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  3 52  0  0  0  0  0  3  0  0  2]
 [ 0  3  0  0  0  0  0  0  9  1  1  0  0 39  0  0  0]
 [ 2  1  1  0  1  2 16  0  0  2  4  1  1 30  0  0  0]
 [ 3  6  0  0  0  0  9  0  0  1 22  0  0 22  0  0  0]
 [ 0  0  0  0  0  1 13  0  0  0  0 12  1 25  0  1  0]
 [ 0  1  7  0  0  0 21  0  1  0  1  0  9 27  0  0  1]
 [ 0  1  0  0  0  1  0  0  0  0  0  0  0 53  0  0  0]
 [ 0  0  0  0  0  0 11  1  0  0  0  0  0 45  0  0  0]
 [ 0  0  1  0  1  2  6  0  0  1  0  1  1 44  0  4  2]
 [ 0  0  5  3  0  2 16  1  0  1  0  0  0 20  0  0 21]]
==================================================
Model: AdaBoost Classifier
Accuracy: 0.21942110177404295
Classification Report:
               precision    recall  f1-score   support

           0       0.16      1.00      0.27        68
           1       1.00      0.61      0.76        72
           2       0.00      0.00      0.00        57
           3       0.00      0.00      0.00        58
           4       0.00      0.00      0.00        66
           5       0.00      0.00      0.00        76
           6       0.24      0.37      0.29        71
           7       0.00      0.00      0.00        61
           8       0.00      0.00      0.00        53
           9       0.00      0.00      0.00        61
          10       0.17      0.06      0.09        63
          11       1.00      0.36      0.53        53
          12       0.13      0.28      0.18        68
          13       0.00      0.00      0.00        55
          14       0.00      0.00      0.00        57
          15       0.00      0.00      0.00        63
          16       0.19      0.80      0.30        69

    accuracy                           0.22      1071
   macro avg       0.17      0.20      0.14      1071
weighted avg       0.17      0.22      0.15      1071

Confusion Matrix:
 [[68  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [28 44  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0 27  0  0  0 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 58]
 [36  0  0  0  0  0  2  0  0  0  2  0 15  0  0  0 11]
 [62  0  0  0  0  0 10  0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 26  0  0  0  1  0 38  0  0  0  6]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 61]
 [53  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [37  0  0  0  0  0 10  0  0  0  3  0 11  0  0  0  0]
 [51  0  0  0  0  0  6  0  0  0  4  0  2  0  0  0  0]
 [23  0  0  0  0  0  8  0  0  0  1 19  2  0  0  0  0]
 [19  0  0  0  0  0 13  0  0  0  1  0 19  0  0  0 16]
 [25  0  0  0  0  0 16  0  0  0  4  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 57]
 [36  0  0  0  0  0 12  0  0  0  4  0  7  0  0  0  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0 55]]
==================================================
Model: Gradient Boosting Classifier
Accuracy: 0.742296918767507
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.79      0.72        68
           1       0.80      0.93      0.86        72
           2       0.60      0.84      0.70        57
           3       0.83      0.91      0.87        58
           4       0.58      0.21      0.31        66
           5       0.48      0.41      0.44        76
           6       0.84      0.99      0.91        71
           7       0.97      0.95      0.96        61
           8       0.76      0.96      0.85        53
           9       0.51      0.43      0.46        61
          10       0.89      0.94      0.91        63
          11       0.72      0.58      0.65        53
          12       0.79      0.68      0.73        68
          13       0.65      0.87      0.74        55
          14       0.88      0.98      0.93        57
          15       0.76      0.59      0.66        63
          16       0.81      0.67      0.73        69

    accuracy                           0.74      1071
   macro avg       0.74      0.75      0.73      1071
weighted avg       0.73      0.74      0.73      1071

Confusion Matrix:
 [[54  2  0  0  1  4  0  0  0  4  1  2  0  0  0  0  0]
 [ 1 67  0  0  0  1  0  0  3  0  0  0  0  0  0  0  0]
 [ 0  0 48  1  1  1  3  0  0  0  0  0  0  0  0  0  3]
 [ 0  0  0 53  0  0  0  1  0  0  0  0  0  0  2  0  2]
 [ 4  4 14  0 14  9  1  0  1  3  2  2  3  2  1  4  2]
 [ 9  3  0  0  2 31  0  0  3 11  0  3  0 11  0  3  0]
 [ 0  0  0  0  0  0 70  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0 58  0  0  0  0  0  0  1  0  0]
 [ 0  2  0  0  0  0  0  0 51  0  0  0  0  0  0  0  0]
 [ 5  0  3  0  1  4  4  0  4 26  2  1  3  4  0  4  0]
 [ 2  1  0  0  0  1  0  0  0  0 59  0  0  0  0  0  0]
 [ 1  3  1  0  2  3  2  0  3  4  0 31  0  3  0  0  0]
 [ 2  0  5  1  1  2  1  0  1  0  1  0 46  2  2  1  3]
 [ 1  0  2  0  0  3  0  0  1  0  0  0  0 48  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  0 56  0  0]
 [ 3  2  2  0  0  6  0  0  0  2  1  4  1  4  0 37  1]
 [ 0  0  5  7  2  0  2  1  0  0  0  0  4  0  2  0 46]]
==================================================
Model: XGBoost Classifier
Accuracy: 0.8253968253968254
Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.88      0.83        68
           1       0.84      0.93      0.88        72
           2       0.78      0.93      0.85        57
           3       0.88      0.91      0.90        58
           4       0.91      0.44      0.59        66
           5       0.51      0.43      0.47        76
           6       0.90      0.97      0.93        71
           7       0.97      0.93      0.95        61
           8       0.85      1.00      0.92        53
           9       0.62      0.67      0.65        61
          10       0.97      0.97      0.97        63
          11       0.76      0.70      0.73        53
          12       0.87      0.91      0.89        68
          13       0.77      0.91      0.83        55
          14       0.90      0.96      0.93        57
          15       0.88      0.71      0.79        63
          16       0.89      0.86      0.87        69

    accuracy                           0.83      1071
   macro avg       0.83      0.83      0.82      1071
weighted avg       0.83      0.83      0.82      1071

Confusion Matrix:
 [[60  3  0  0  0  1  0  0  0  2  0  1  0  1  0  0  0]
 [ 1 67  0  0  0  0  0  0  1  1  0  0  2  0  0  0  0]
 [ 0  0 53  0  0  1  2  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0 53  0  0  0  1  0  0  0  0  0  0  2  0  2]
 [ 4  3  7  0 29  8  1  0  1  5  2  0  1  0  1  3  1]
 [ 7  4  0  0  0 33  2  0  1 11  0  6  1 10  0  1  0]
 [ 0  0  0  0  0  0 69  0  0  1  0  0  1  0  0  0  0]
 [ 0  0  0  3  0  0  0 57  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0  0  0  0 53  0  0  0  0  0  0  0  0]
 [ 1  0  3  0  0  9  1  0  2 41  0  1  3  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  0 61  0  0  1  0  0  0]
 [ 1  2  0  0  0  5  2  0  2  3  0 37  0  1  0  0  0]
 [ 0  0  1  0  1  1  0  0  1  0  0  0 62  0  2  0  0]
 [ 0  0  1  0  0  2  0  0  0  0  0  0  0 50  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 55  0  2]
 [ 2  1  0  0  1  5  0  0  0  2  0  4  1  2  0 45  0]
 [ 0  0  3  4  1  0  0  1  0  0  0  0  0  0  1  0 59]]

In [27]:
!pip install xgboost

Collecting xgboost
  Using cached xgboost-3.0.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\singh\pycharmprojects\education recommendor\.venv\lib\site-packages (from xgboost) (2.2.4)
Requirement already satisfied: scipy in c:\users\singh\pycharmprojects\education recommendor\.venv\lib\site-packages (from xgboost) (1.15.2)
Using cached xgboost-3.0.0-py3-none-win_amd64.whl (150.0 MB)
Installing collected packages: xgboost
Successfully installed xgboost-3.0.0

In [29]:
#Model Selection (Random Forest)
model = RandomForestClassifier()

model.fit(X_train_scaled, y_train)
# Predict on test set
y_pred = model.predict(X_test_scaled)

# Calculate metrics
print("Accuracy: ",accuracy_score(y_test, y_pred))
print("Report: ",classification_report(y_test, y_pred))
print("Confusion Matrix: ",confusion_matrix(y_test, y_pred))

Accuracy:  0.8253968253968254
Report:                precision    recall  f1-score   support

           0       0.80      0.87      0.83        68
           1       0.77      0.99      0.87        72
           2       0.74      0.96      0.84        57
           3       0.90      0.93      0.92        58
           4       0.85      0.42      0.57        66
           5       0.56      0.36      0.44        76
           6       0.92      1.00      0.96        71
           7       0.93      0.93      0.93        61
           8       0.76      0.98      0.86        53
           9       0.63      0.67      0.65        61
          10       0.89      0.98      0.93        63
          11       0.88      0.72      0.79        53
          12       0.90      0.82      0.86        68
          13       0.78      0.91      0.84        55
          14       0.90      0.98      0.94        57
          15       0.91      0.79      0.85        63
          16       0.90      0.83      0.86        69

    accuracy                           0.83      1071
   macro avg       0.83      0.83      0.82      1071
weighted avg       0.82      0.83      0.81      1071

Confusion Matrix:  [[59  5  0  0  1  0  0  0  0  1  1  0  0  0  0  1  0]
 [ 0 71  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 55  0  0  0  1  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0 54  0  0  0  1  0  0  0  0  0  0  2  0  1]
 [ 4  2  9  0 28  7  0  0  1  6  2  2  2  0  1  0  2]
 [ 5  7  1  0  1 27  1  0  6 12  0  2  1 11  0  2  0]
 [ 0  0  0  0  0  0 71  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0 57  0  0  0  0  0  0  2  0  1]
 [ 0  1  0  0  0  0  0  0 52  0  0  0  0  0  0  0  0]
 [ 4  1  1  0  0  3  2  0  2 41  2  1  3  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  1  0 62  0  0  0  0  0  0]
 [ 0  1  0  0  2  6  0  0  3  1  1 38  0  1  0  0  0]
 [ 0  1  2  0  1  1  2  0  0  1  2  0 56  0  1  0  1]
 [ 0  0  2  0  0  0  0  0  2  0  0  0  0 50  0  1  0]
 [ 0  0  0  0  0  0  0  1  0  0  0  0  0  0 56  0  0]
 [ 2  3  0  0  0  3  0  0  0  3  0  0  0  2  0 50  0]
 [ 0  0  4  5  0  0  0  2  1  0  0  0  0  0  0  0 57]]

In [30]:
#Recommendation System
class_names = ['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
               'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
               'Banker', 'Writer', 'Accountant', 'Designer',
               'Construction Engineer', 'Game Developer', 'Stock Investor',
               'Real Estate Developer']

def Recommendations(gender, part_time_job, absence_days, extracurricular_activities,
                    weekly_self_study_hours, math_score, history_score, physics_score,
                    chemistry_score, biology_score, english_score, geography_score,
                    total_score,average_score):
     # Encode categorical variables
    gender_encoded = 1 if gender.lower() == 'female' else 0
    part_time_job_encoded = 1 if part_time_job else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0

    # Create feature array
    feature_array = np.array([[gender_encoded, part_time_job_encoded, absence_days, extracurricular_activities_encoded,
                               weekly_self_study_hours, math_score, history_score, physics_score,
                               chemistry_score, biology_score, english_score, geography_score,total_score,average_score]])

    # Scale features
    scaled_features = scaler.transform(feature_array)
     # Predict using the model
    probabilities = model.predict_proba(scaled_features)

    # Get top five predicted classes along with their probabilities
    top_classes_idx = np.argsort(-probabilities[0])[:5]
    top_classes_names_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]

    return top_classes_names_probs

In [31]:
# Example usage 1
final_recommendations = Recommendations(gender='female',
                                        part_time_job=True,
                                        absence_days=10,
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=7,
                                        math_score=65,
                                        history_score=60,
                                        physics_score=97,
                                        chemistry_score=94,
                                        biology_score=71,
                                        english_score=81,
                                        geography_score=66,
                                        total_score=534,
                                        average_score=76.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
==================================================
Teacher with probability 0.37
Business Owner with probability 0.34
Unknown with probability 0.15
Government Officer with probability 0.04
Real Estate Developer with probability 0.03

In [32]:
print("Predicted Label:", model.predict(X_test_scaled[9].reshape(1,-1)))
print("Actual:", y_test.iloc[9])

Predicted Label: [8]
Actual: 8

In [33]:
print("Predicted Label:", model.predict(X_test_scaled[800].reshape(1,-1)))
print("Actual:", y_test.iloc[800])

Predicted Label: [16]
Actual: 16

In [34]:
import pickle

In [35]:
import os
os.makedirs("Models", exist_ok = True)
pickle.dump(scaler, open("Models/scaler.pkl",'wb'))
pickle.dump(model, open("Models/model.pkl", 'wb'))

In [36]:
scaler = pickle.load(open("Models/scaler.pkl",'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))

In [37]:
import sklearn

In [38]:
print(sklearn.__version__)

1.6.1